CREATE TABLE CUSTOMER_REWARDS (
    reward_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_email VARCHAR2(255) NOT NULL,
    gift_id NUMBER NOT NULL,
    reward_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_gift
        FOREIGN KEY (gift_id)
        REFERENCES gift_catalog(gift_id),
    CONSTRAINT fk_customer
        FOREIGN KEY (customer_email)
        REFERENCES customers(email_address)
);